<a href="https://colab.research.google.com/github/DataLovecraft/DS-Unit-1-Sprint-4-Linear-Algebra/blob/master/module3-dimensionality-reduction/Assignment_High_Dimensional_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vertical Line Test

## 1.1 Create two graphs, one that passes the vertical line test and one that does not.

In [0]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [4]:
x = [1, 2, 3]
y = [2, 4, 1]

plt.title('Passes the line test')

plt.plot(x, y)
plt.show;

In [8]:
x = np.linspace(0, 1, 101)
y_a = x ** (0.5)
y_b = y_a * (-1)
y_c = x **2

plt.plot(x, y_a)
plt.plot(x, y_b)

plt.title('Does not pass the line test')
plt.show();

## 1.2 Why are graphs that don't pass the vertical line test not considered "functions?"

A function has to have one input mapped to one output

# Functions as Relations

## 2.1 Which of the following relations are functions? Why?

\begin{align}
\text{Relation 1: } \{(1, 2), (3, 2), (1, 3)\}
\\
\text{Relation 2: } \{(1, 3), (2, 3), (6, 7)\}
\\
\text{Relation 3: } \{(9, 4), (2, 1), (9, 6)\}
\\
\text{Relation 4: } \{(6, 2), (8, 3), (6, 4)\}
\\
\text{Relation 5: } \{(2, 6), (2, 7), (2, 4)\}
\end{align}

Number 2 is a function. All the other listed relations have an x value repeated with a different associated y value.


# Functions as a mapping between dimensions


## 3.1 for the following functions what is the dimensionality of the domain (input) and codomain (range/output)?

\begin{align}
m(𝑥_1,𝑥_2,𝑥_3)=(x_1+x_2, x_1+x_3, x_2+x_3)
\\
n(𝑥_1,𝑥_2,𝑥_3,𝑥_4)=(x_2^2 + x_3, x_2x_4)
\end{align}



For m:

Dimensionality of input = 3 Dimensionality of output = 3

For n:

Dimensionality of input = 4 Dimensionality of output = 2

## 3.2 Do you think it's possible to create a function that maps from a lower dimensional space to a higher dimensional space? If so, provide an example.

You can indeed have a linear map from a "low-dimensional" space to a "high-dimensional". One such example is: 
𝑓(𝑥)=(𝑥,𝑥)

 

# Vector Transformations

## 4.1 Plug the corresponding unit vectors into each function. Use the output vectors to create a transformation matrix.

\begin{align}
p(\begin{bmatrix}x_1 \\ x_2 \end{bmatrix}) = \begin{bmatrix} x_1 + 3x_2 \\2 x_2 - x_1 \\  \end{bmatrix}
\\
\\
q(\begin{bmatrix}x_1 \\ x_2 \\ x_3\end{bmatrix}) = \begin{bmatrix} 4x_1 + x_2 + 2x_3 \\2 x_2 - x_1 + 3x_3 \\ 5x_1 - 2x_3 + x_2  \end{bmatrix}
\end{align}

In [12]:
unit_2d = np.array([[1,0], [0, 1]])
unit_3d = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

p = np.matmul(np.array([[1, 3], [-1, 2]]), unit_2d)
print('p:', p)

q = np.matmul(np.array([[4, 1, 2], [-1, 2, 3], [5, 1, -2]]), unit_3d)
print('q:', q)



p: [[ 1  3]
 [-1  2]]
q: [[ 4  1  2]
 [-1  2  3]
 [ 5  1 -2]]


## 4.2 Verify that your transformation matrices are correct by choosing an input matrix and calculating the result both via the traditional functions above and also via vector-matrix multiplication.

In [0]:
P = np.array([[1, 3], [-1, 2]])
Q = np.array([[4, 1, 2], [-1, 2, 3], [5, 1, -2]])


# Eigenvalues and Eigenvectors

## 5.1 In your own words, give an explanation for the intuition behind eigenvalues and eigenvectors.

A Eigenvector is a vector in which a matrix tranformation rotates around. 

A Eigenvalue scales a Eigenvalue. 


# The Curse of Dimensionality

## 6.1 What are some of the challenges of working with high dimensional spaces?

Human brains are not great at imagining dimensions greater than 3. 
Higher dimensions in data can lead to overfitting. 

## 6.2 What is the rule of thumb for how many observations you should have compared to parameters in your model?

At least five times as many observations as there are features. 

# Principal Component Analysis

## 7.1 Load the UCI Machine Learning Repository's [Iris Dataset](https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/d546eaee765268bf2f487608c537c05e22e4b221/iris.csv) and use PCA to isolate the dataset's first and second principal components and plot them on a graph. 

In [39]:
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/d546eaee765268bf2f487608c537c05e22e4b221/iris.csv"

df = pd.read_csv(url)
print(df.shape)
df.head()

(150, 5)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [40]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [41]:
from sklearn.preprocessing import StandardScaler

features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

# Features
X = df.loc[:, features].values

# Target
y = df.loc[:, ['species']].values

# Standardize the Data
std_X = StandardScaler().fit_transform(X)

print(std_X)
                                  

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e

In [43]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)

principal_components = pca.fit_transform(X)

principal_df = pd.DataFrame(data = principal_components, columns = ['principal component 1', 'principal component 2'])

principal_df.head()

principal component 1  principal component 2
0              -2.684207               0.326607
1              -2.715391              -0.169557
2              -2.889820              -0.137346
3              -2.746437              -0.311124
4              -2.728593               0.333925

In [45]:
final_df = pd.concat([principal_df, df[['species']]], axis = 1)

final_df.head()

principal component 1  principal component 2 species
0              -2.684207               0.326607  setosa
1              -2.715391              -0.169557  setosa
2              -2.889820              -0.137346  setosa
3              -2.746437              -0.311124  setosa
4              -2.728593               0.333925  setosa

In [54]:
fig = plt.figure(figsize = (8,8))

ax = fig.add_subplot(1, 1, 1)
ax.set_xlabel('Principal Component 1', fontsize = 15)
ax.set_ylabel('Principal Component 2', fontsize = 15)
ax.set_title('2 component CPA', fontsize = 20)

species = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
colors = ['r', 'g', 'b']
for target, color in zip(species, colors):
    indicesToKeep = final_df['species'] == species
    ax.scatter(final_df.loc[indicesToKeep, 'principal component 1']
               , final_df.loc[indicesToKeep, 'principal component 2']
               , c = color
               , s = 50)
ax.legend(species)
ax.grid()

ValueError: ignored

# Stretch Goal

## 1) Do NOT work on the stretch goal until you feel like you have a firm grasp of eigenvectors, eigenvalues, and PCA. Prioritize self-study over the stretch goal if you are not comfortable with those topics yet.

## 2) Explore further the intuition behind eigenvalues and eigenvectors by creating your very own eigenfaces:

<center>![Eigenfaces](https://i.pinimg.com/236x/1c/f1/01/1cf101a9859437a5d096a04b05be06b4--faces-tattoo.jpg)</center>

You don't necessarily have to use this resource, but this will get you started: 
[Eigenface Tutorial](https://sandipanweb.wordpress.com/2018/01/06/eigenfaces-and-a-simple-face-detector-with-pca-svd-in-python/)